# Generated by Django 5.2.13 on 2026-05-01 20:25

import django.core.validators
import my_music.music.validatiors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[my_music.music.validatiors.validators_username, django.core.validators.MinLengthValidator(2)]),
        ),
    ]
