# Generated by Django 5.2.13 on 2026-05-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Hart Metal', 'Hart Metal'), ('BG Estrada Music', 'BG Estrada Music'), ('Chalga Music', 'Chalga Music'), ('Pop Music', 'Pop Music'), ('Jazz Music', 'Jazz Music'), ('R&B Music', 'R&B Music'), ('Rock Music', 'Rock Music'), ('Country Music', 'Country Music'), ('Dance Music', 'Dance Music'), ('Hip Hop Music', 'Hip Hop Music'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
    ]
