# Generated by Django 5.2.13 on 2026-05-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_album_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.URLField(unique=True, verbose_name='Image URL'),
        ),
    ]
