# Generated by Django 5.2.13 on 2026-05-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
